name: 'semantic_layer_demo'
version: '1.0.0'
config-version: 2
profile: 'default'
model-paths: ["models"]
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         
  - "target"
  - "dbt_packages"

models:
  semantic_layer_demo:
    marts:
      +materialized: table
    semantic_layer:
      +materialized: table
    staging:
      +materialized: view
